# Generated by Django 5.2.1 on 2025-08-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=100, unique=True)),
                ('reviewer_name', models.CharField(max_length=255)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('review_date', models.DateField()),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10)),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
